// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaDNjdNS8_TOjI1M_hGWqdVdvxnksBZ90',
    appId: '1:302941484921:web:dc757ba27abe26ab3d21a8',
    messagingSenderId: '302941484921',
    projectId: 'project-1226141972119082710',
    authDomain: 'project-1226141972119082710.firebaseapp.com',
    storageBucket: 'project-1226141972119082710.firebasestorage.app',
    measurementId: 'G-P38VRR1Y04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw08Pq51Y_i4zLZumhhtYrezoTq8iFkwA',
    appId: '1:302941484921:android:161af3e11442710c3d21a8',
    messagingSenderId: '302941484921',
    projectId: 'project-1226141972119082710',
    storageBucket: 'project-1226141972119082710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_caTicl39urLRcFBsWFmYSsVYmd1dVk',
    appId: '1:302941484921:ios:af655cf3defab23f3d21a8',
    messagingSenderId: '302941484921',
    projectId: 'project-1226141972119082710',
    storageBucket: 'project-1226141972119082710.firebasestorage.app',
    iosBundleId: 'com.example.appSach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_caTicl39urLRcFBsWFmYSsVYmd1dVk',
    appId: '1:302941484921:ios:af655cf3defab23f3d21a8',
    messagingSenderId: '302941484921',
    projectId: 'project-1226141972119082710',
    storageBucket: 'project-1226141972119082710.firebasestorage.app',
    iosBundleId: 'com.example.appSach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaDNjdNS8_TOjI1M_hGWqdVdvxnksBZ90',
    appId: '1:302941484921:web:0f3c6d3f3148129a3d21a8',
    messagingSenderId: '302941484921',
    projectId: 'project-1226141972119082710',
    authDomain: 'project-1226141972119082710.firebaseapp.com',
    storageBucket: 'project-1226141972119082710.firebasestorage.app',
    measurementId: 'G-D4BT3BB8J3',
  );
}
